spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_password}
  jpa:
      show-sql: true
      properties:
        hibernate:
          default_batch_fetch_size: 1000
      hibernate:
        ddl-auto: update
# 포트 변경
server:
  port: 8083

# # H2 db 연결 정보
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     username: sa
#     password:
#     driver-class-name: org.h2.Driver

# # H2 콘솔 활성화
#   h2:
#     console:
#         enabled: true

  # jpa:
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       default_batch_fetch_size: 1000
  #   hibernate:
  #     ddl-auto: update

jwt:
  secret:
    key: ${SECRET_KEY}